# Generated by Django 2.2 on 2022-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
